version: "3"

services:
  pdf2png:
    build:
      context: .
      # target: dev
    image: francajosejunior/pdf2png
    # container_name: pdf2png
    volumes:
      - ./:/usr/src/app
    expose:
      - 80
    environment:
      NODE_ENV: "production"
      PORT: 80
    command: node src/index.js

  nginx:
    image: nginx:1.17.6-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    container_name: nginx
    ports:
      - 3232:80
    depends_on:
      - pdf2png
